name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print cargo version
      run: cargo --version
    - name: Check fmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
